### ISSUE TITLE
Neofetch corrupts the font

### ISSUE THREAD

**Issue by paulodelgado** [onflapp/gs-terminal#1]
This happens on both the Terminal.app distributed in Debian and the GNUstep Desktop version of Terminal.app.  I figured I'd post here since this repo has more activity.

After running neofetch the font/encoding gets garbled and one has to close the window and open a new one.  Its just a bit of an annoyance but I figured its important to get people to show off their GNUstep desktops.

![neofetch_wrecks_terminal](https://github.com/onflapp/gs-terminal/assets/254779/e7c51d6d-ea71-4771-b52c-4ba18d795002)

**Comment by onflapp** [comment]
The terminal got confused by 256 color escape sequences. It should work now.
