### ISSUE TITLE
scrollWheel:(NSEvent*) defined twice in TerminalKit/TerminalView.m

### ISSUE THREAD

**Issue by mclarenlabs** [onflapp/gs-terminal#2]
I noticed the scroll wheel did not scroll the terminal view to look at history.  On my system, other GS apps handle scroll wheel just fine.

After some debugging, I found two definitions of scrollWheel: in TerminalKit/TerminalView.m

- the first def implements scrolling of view history - category TerminalView(scrolling)
- the second def sends events to the terminal parser - category TerminalView(selection)

It looks like the second def was added in May 2022, shadowing the first.  Commenting out the second gives nice scrollwheel history behavior as expected.

Not sure the best way to fix.  Reporting here.

Overall, Terminal.app is solid, in my experience, and nice to use.

**Comment by onflapp** [comment]
Well spotted. The default scrollWheel implementation conflicted with mouse handling code. It should be fixed now.
